name = "RegistryIndexer"
uuid = "7771acb3-bd87-4d1b-b714-69a46162fa2f"
authors = ["AbdulrhmnGhanem <abdoghanem160@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
